### ISSUE TITLE
Upgrade com.spotify:docker-client dependency

### ISSUE THREAD

**Issue by cleankod** [geowarin/docker-junit-rule#10]
Current version is: [![Maven Central](https://img.shields.io/maven-central/v/com.spotify/docker-client.svg)](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.spotify%22%20docker-client). This version contains `ShmSize` in `HostConfig` which is is a prerequisite for me, in order to start an Oracle container.

**Comment by geowarin** [comment]
Released in v1.2.0
