### ISSUE TITLE
container is not destroyed after test

### ISSUE THREAD

**Issue by SaltOfTheFlame** [geowarin/docker-junit-rule#2]
container is not destroyed after running tests

**Comment by geowarin** [comment]
Weird...

https://github.com/geowarin/docker-junit-rule/blob/8e5373c15ceed67fe4161cd64e5fbe6c4cd63ef2/src/main/java/com/github/geowarin/junit/DockerRule.java#L78-L87

**Comment by geowarin** [comment]
I'm closing it as I don't know what else the lib can do to destroy the container...
Please reopen if you are still experiencing the issue
